# Generated by Django 5.1.5 on 2025-03-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('product_img', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('product_review', models.TextField()),
                ('count', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
            ],
        ),
    ]
